apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "langflow.fullname" . }}
  labels:
    {{- include "langflow.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "langflow.selectorLabels" . | nindent 6 }}